version: '3.8'

services:
  loadbalancer:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - app1
      - app2
      - app3

  app1:
    image: jyothiram266/go-app:v1
    expose:
      - "8080"

  app2:
    image: jyothiram266/app-blue:v1
    expose:
      - "80"

  app3:
    image: jyothiram266/app-blue:v2
    expose:
      - "80"
